---
- name: copy custom yum repo
  template: 
    src=nginx.repo.j2
    dest=/etc/yum.repos.d/nginx.repo
- name: install nginx
  yum:
    name: nginx
    state: latest
- name: Copy custom configuration to /etc/nginx
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
- name: Copy Reverse proxy details
  template:
    src=defaults.conf.j2
    dest=/etc/nginx/conf.d/defaults.conf
- name: start the server
  service:
    name: nginx
    state: started
    enabled: yes
